// Generated by scripts/generate-family-data.mjs - do not edit by hand.
export const allowlist = [
  "family/DSC00355.JPG",
  "family/DSC00662.JPG",
  "family/DSC02332.JPG",
  "family/DSC04284.JPG",
  "family/DSC04503.JPG",
  "family/DSC04732.JPG",
  "family/DSC04766.JPG",
  "family/DSC04928.JPG",
  "family/DSC05409.JPG",
  "family/DSC05590.JPG",
  "family/DSC06076.JPG"
];

export const photos = [
  {
    "path": "family/DSC00355.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC00662.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC02332.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC04284.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC04503.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC04732.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC04766.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC04928.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC05409.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC05590.JPG",
    "alt": "Family photo"
  },
  {
    "path": "family/DSC06076.JPG",
    "alt": "Family photo"
  }
];

